#-*-coding:utf-8-*-

cmds = [
    "python main_imagenet.py --budget -1 --model MobileNetV2 -s exp/baseline/mobilenet_full --model_cfg baseline_full --batchsize 128",
    "python main_imagenet.py --model MobileNetV2 --model_cfg baseline_full --lr 0.001 --epochs 160 --scheduler cosine_anneal_warmup --input_resolution --batchsize 72 --channel_unit_type fc_gumbel --pooling_method ave --budget 0.5 --loss_args layer_wise --unlimited_lower -s exp/spatial_channel_gumbel_mobile/s50_c50_ave_g32 --group_size 32 --channel_budget 0.5 --channel_stage 6 -1 --lasso_lambda 1 --epochs 120 --no_attention --mask_kernel 1 --load ",
    "python main_imagenet.py --model_args hardware_2048 --lr 0.01 --input_resolution --pooling_method ave --batchsize 256 --epochs 160 --scheduler cosine_anneal_warmup --channel_unit_type fc_gumbel --budget 0.5 --loss_args layer_wise --unlimited_lower -s exp/spatial_channel_gumbel/s50_c50_ave_g64_stage23-layerblock --lasso_lambda 1 --group_size 64 --lasso_lambda 1 --channel_budget 0.5 --channel_stage 2 3 --load "'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.50 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s50_c75_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',

    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.50 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s50_c50_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.50 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.50 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s50_c25_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.75 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s75_c75_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.75 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s75_c50_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.50 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.75 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s75_c25_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.25 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s25_c75_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.25 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s25_c50_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.50 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --input_resolution --budget 0.25 --unlimited_lower -s exp/cifar_ave_spatial_channel_nomix_step/s25_c25_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.50 -s exp/cifar_ave_spatial_channel_nomix/s50_c75_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.50 -s exp/cifar_ave_spatial_channel_nomix/s50_c50_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.5 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention ',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.50 -s exp/cifar_ave_spatial_channel_nomix/s50_c25_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.75 -s exp/cifar_ave_spatial_channel_nomix/s75_c75_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.75 -s exp/cifar_ave_spatial_channel_nomix/s75_c50_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.5 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention ',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.75 -s exp/cifar_ave_spatial_channel_nomix/s75_c25_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.25 -s exp/cifar_ave_spatial_channel_nomix/s25_c75_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.75 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.25 -s exp/cifar_ave_spatial_channel_nomix/s25_c50_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.5 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention ',
    # 'CUDA_VISIBLE_DEVICES=0 python main_cifar.py --channel_unit_type fc_gumbel --pooling_method ave --scheduler cosine_anneal_warmup --resolution_mask --input_resolution  --unlimited_lower --budget 0.25 -s exp/cifar_ave_spatial_channel_nomix/s25_c25_resmask_ave --load exp_before_ddl/cifar_spatial_channel/baseline/checkpoint_best.pth --group_size 8 --batchsize 224 --channel_budget 0.25 --channel_stage 1 2 --mask_type conv --net_weight 0 --valid_range 1 --mask_kernel 1 --no_attention',
]

import os
log = open("train_log.log", "a+")
for idx, cmd in enumerate(cmds):
    log.write(cmd)
    log.write("\n")
    # print("Processing cmd {}".format(idx))
    os.system(cmd)
